### ISSUE TITLE
Download-Duplicates Without Matching Group Name

### ISSUE THREAD

**Issue by skiski456** [autodl-community/autodl-irssi#101]
If it's not too difficult, can you add an option to only match the name, episode number, source, quality to exclude duplicates? I'd like to use multiple sites for my filters and only get the first release regardless of the group.

If you point me to the relevant part of the code I can take a look myself.

Thanks,

ski

**Comment by thebigmunch** [comment]
No. That would defeat the entire point of download-duplicates.

What you want is #59, but, as much as I've tried, I can't get anyone who actually wants to test it. So, despite having a reasonably working version of it for over a year, I simply can't release it due to lack of testing as I don't have the means to test certain aspects of it (the exact use case you have for one).

If you're interested in testing this feature, come to the IRC channel.
