### ISSUE TITLE
Error getting files listing: Error: Could not decode json string

### ISSUE THREAD

**Issue by Pelllicer** [autodl-community/autodl-irssi#107]
After installing autodl-rutorrent following the guide on the wiki I'm getting this error on the rutorrent gui log:
`Error downloading files. Make sure autodl-irssi is started and configured properly (eg. password, port number): Error getting files listing: Error: Could not decode json string`.

My php version is the latest one and have sockets, json and xml installed by default. I still added:
```
extension=sockets.so
extension=json.so
extension=xml.so

```
To both `/etc/php5/cli/php.ini` and `/etc/php5/apache2/php.ini` but either ways I'm still getting the same error always no matter what combination I try.
* SO: Debian Jessie.
* PHP: 5.6.22-0+deb8u1.
I can provide any adittional info from phphinfo if needed. Any clue what could be the source of this error? Could it be related maybe to a json_encode/decode bug fixed in this last version (http://php.net/ChangeLog-5.php)? Thank you.

**Comment by thebigmunch** [comment]
As stated in the contributing guidelines, this should've been posted on the ruTorrent plugin issue tracker. Also, you should test different versions of PHP yourself to see. I spend very little effort on the ruTorrent plugin. If you can show that there's something to change/fix in it, I will. Otherwise, it will likely sit in the issue tracker for a long time unless a large number of people run into the same issue.
