### ISSUE TITLE
[wishlist] Ability to make irc bots reconnect, and/or retrieve connection status.

### ISSUE THREAD

**Issue by ngnh** [autodl-community/autodl-irssi#143]
There's no way to tell if the bot is online in all channels unless you connect to the network from a separate client and then whois the bot. Would be nice if there was an option to make the bots reconnect to the network and channels. And be able to retrieve the connection status from the bot.

**Comment by thebigmunch** [comment]
You don't need to connect with a separate client. autodl-irssi is a plugin for the irssi IRC client. Opening the irssi client and checking there would be the way to do it. autodl-irssi also automatically tries reconnecting and rejoining, so not sure what situation you're running into where it's not.

It's possible to add slash commands for forcing a reconnect, but the same thing can be accomplished already with ``/autodl reload``. It's not available in the ruTorrent plugin, because it caused problems when used from ruTorrent that I didn't feel was worth the pain of figuring out.

As for showing connected servers and joined channels, that's also possible. I just don't think I'd spend any time on it myself. And, pretty much all 'help wanted' features requests never get done unless I, for some reason, get the urge to do them some day.

**Comment by ngnh** [comment]
Thanks for your answer. I didn't know it automatically attempts to reconnect to disconnected server/channels. But it is good to know. I'd had a few situations where i didn't catch something and i didn't know why, used a separate client to verify it was online and monitoring. I only use rutorrent for the webui and the autodl-irssi tab. I'm running it in a vm on a windows server. Which is why i had to use a separate client to verify the bot was online.
But at least now i know it will try to reconnect if something happens.

**Comment by ashmandias** [comment]
"Which is why i had to use a separate client to verify the bot was online."

I don't follow. If you are running autodl-irssi, you, by definition, have irssi running, and can use that to check the bot status directly.
