### ISSUE TITLE
discord invite expired

### ISSUE THREAD

**Issue by Rhodesia** [autodl-community/autodl-irssi#165]
idk if this is the right place to ask but the discord invite in contributing.md is broken

**Comment by thebigmunch** [comment]
Oops. Missed the link in that file when I was removing Discord references.

I have deleted the Discord server. And while I never promised user support, I have now made official that I don't provide user support. So, I've simply lessened my load. You may still find support from other users on IRC.

This has been a long time coming due to many entitled douchebags killing my desire to help anyone or do any FOSS work/support, let alone on autodl. The final straw was someone on Discord getting pissy because I wouldn't help them with an issue in DMs after I helped them with something else in the channel.

Here's what they had to say: 
![2018-09-06_14-54-09](https://user-images.githubusercontent.com/118418/45602107-1a520680-b9e6-11e8-87a3-0ac71e1dd3fc.png)

I've had people question this before due to my adding donation/referral links upon requests by multiple users. I posted a response before deleting the server that I'll repeat here for more exposure, with some additional explanation.

----------

Being generous, I average $5-10 per year in donations from this project. Honestly, that's actually more than I expected. However...

If you were to take my time supporting users and my time spent developing/maintaining autodl and applied entry-level programmer and support pay to it, you'd find I've put thousands of dollars worth of my free time into this project.

There was a time when BitBucket and GitHub killed their download sections where I payed for a server to host releases for the updater. Even though it was very cheap, the duration of that definitely cost me the entirety of donations I've ever made off this project or more. I even kept it alive for quite some time after GitHub released its Releases feature. Partly because I was strapped for extra time and partly because I knew many people would throw a fit if the updater was changed again. And, yes, many people threw a fit when that happened.

It should be noted that when I took on this project, I didn't even use autodl-irssi. In fact, I didn't start using it for about 6 months after.

I saw many people asking in the Whatbox help channel about broken trackers, etc. I saw some disparate people on tracker forums providing updated or new tracker files (often poorly executed). I saw no central place for help and no way to get new features or fix any issues that would come up (the SNI issue particularly comes to mind). I being one who likes to help, and also could, jumped in to try to create a community project.

In some ways it happened. But in terms of creating a supportive community, it failed miserably.  Right now in IRC, there are 30 users. Many of those are just idlers. At most there have been 50-60. Meanwhile, the latest download numbers: ``autodl: 131485 in 1 week 1 day 6 hours 30 minutes 58 seconds`` / ``trackers: 89931 in 5 days 5 hours 11 minutes 24 seconds``.

I added Discord as an experiment to see if it attracted more users than IRC. It didn't. Nobody wants to pitch in and help the way I did. And I still do want to help, but, for my happiness and that of those closest to me, I have to limit it to specific dev things when I have time and motivation. But I won't lie; I considered just dropping autodl altogether. Even just deleting the repos outright.

There's still opportunity for autodl users to come together and pitch in as I had hoped, but I'm not holding my breath.

----------

Thanks for the report (and hopefully the read).
