### ISSUE TITLE
Add IMDB or TVDB/TMDB Lookup

### ISSUE THREAD

**Issue by ghost** [autodl-community/autodl-irssi#32]
It would be beneficial to only autodl good movies, and not bad ones

[Flexget's imdb plugin](http://flexget.com/wiki/Plugins/imdb) implementation is great since it includes genre, vote counts, and votes.  

This is low on the list of todo, but I wanted to write ideas down.

**Comment by thebigmunch** [comment]
So, the way to do this is probably to set up our own DB and API for this; I don't want to rely on or hammer any 3rd-party services. This brings up a few issues:

* What level of server would be needed to support the number of requests?
* Am I willing to pay for said level of server out of my own pocket, because even if donations were received, they simply can't be counted on?
* Is there a good way to prevent unwanted clients (people not using autodl-irssi) from using it?
* Is there anyone other than me willing to write the software necessary to grab the IMDB info, parse it into a DB, and possibly the code to make it available through the web?

Another solution would be to have the clients do it locally if they have IMDB lookups enabled. I'm not really a fan of this, but I might be convinced.

The last and possibly best way is to just use [TVDB](http://thetvdb.com/) instead and have people provide their API key in the settings if they want to use it. This would likely be much easier, more reliable, and more secure way to provide something like this. But, I know a lot of people just prefer IMDB.

Thoughts? Interest?

**Comment by jonnyboy** [comment]
I am not sure if you know about this site, [OMDB Api](http://www.ombapi.com/). But, he has already done the work and the api is free. You only need an apikey if you want to download the images.

**Comment by thebigmunch** [comment]
Yes, I'm aware of it and some other sites like the one I linked above. But, the number of requests could get excessive for a 3rd-party service. Most of which have an requests limit or would certainly do something about excessive use. And it would be easy for them to ban all autodl requests by user agent.

Unless someone wants to arrange something or volunteer a service for IMDB lookup, I'll probably just move forward with TVDB lookup for the time being.

**Comment by thebigmunch** [comment]
[OMDb API](http://www.omdbapi.com/) will be moving to API keys soon to prevent abuse by some bots. When this happens, the request limit go away. The possibility then opens up to add IMDB support using it and requiring people to enter their own API key if they want to use IMDB lookup. I'd still like it if some interested party checked with OMDb API's admin to see if they'd be against its use in something like autodl-irssi; don't feel like implementing this only to have users get banned or, wrose, the autodl-irssi user-agent get banned.

**Comment by mrbeers2232** [comment]
I can only wish I was capable of helping with this.
I know for a fact that this is in very high demand.
Some people are scripting it so autodl only receives a list of IMDb checked movies, some are running a script that checks IMDb based on the autodl output, then adds it to the torrent client.

I don't know how easy this would be, but maybe add plugin capability? Plugin a custom .sh script that can run before or after the autodl process?
