### ISSUE TITLE
Major revision - v2.0.0

### ISSUE THREAD

**Issue by thebigmunch** [autodl-community/autodl-irssi#37]
These are changes that would break compatibility or might otherwise warrant a new major revision. This issue will keep track of these issues.
- [ ] Add FTPS and SFTP support to the FTP action [#3]
- [ ] Change to  [semantic-style versioning](http://semver.org/) (Perl doesn't support the full spec, but we don't really need those features)
- [ ] Constants overhaul [ #25 ]
- [ ] Filter options refresh and refactor [#88]

**Comment by CoinflickerZombie** [comment]
I have had many seedbox providers.. And Xirvik is the best.. So even if I now have a 30TB at ovh I still keep on box at Xirvik.com because they do and want develope and be best. support@xirvik.com or you can contact me. Admin on one of the oldest trackers with complete rebuild of the u-232 source and I have many accounts and people that can offer resources that I experience many times is a problem.
And seedboxes at xirvik even have all dedicated connected with shout and many premium people that love this stuff :) TTi 2005 Now Ti...  Welcome :)

**Comment by rahul0705** [comment]
Any chance for full ZNC support on 2.0.0?

**Comment by Cyber-Surfer** [comment]
Yes.. I've been banging my head on my desk trying to get v1.65 and v2.65 of the trackers to work with ruTorrent v3.8 and ZNC v1.7 and have had no luck.. I don' t have SSH access so I have no idea what kind of problems it's having (if any), but it doesn't want to seem to connect to ZNC... So full ZNC support would be great..

**Comment by ashmandias** [comment]
I use autodl with ZNC, and have for several years. The trick is to just set up a different domain name for each tracker (be lazy, use afraid.org and wildcard DNS). After that, everything works 100% as expected in autodl. It is my understanding that this is due to the original (pre-thebigmunch) autodl-irssi using irc domain names as unique tokens internally.

**Comment by thebigmunch** [comment]
Closing this and subtasks as unlikely to happen. If I were to undertake these things myself, it would actually take less time and effort to write a new piece of software from scratch in a sane language.
