### ISSUE TITLE
Add support for new rtorrent function names

### ISSUE THREAD

**Issue by Sparticuz** [autodl-community/autodl-irssi#74]
Since version 0.9.0, rtorrent has deprecated many commands. If you are using anything newer than 0.9.4, then autodl does not work because load_start has been changed to load.start. I tried to change the only instance I could find of load_start to load.start, but it didn't work. (it was in MatchedRelease.pm)

**Comment by thebigmunch** [comment]
I can't replicate this issue. Everything works fine with rTorrent 0.9.4 for me. I also can't find any reference to any kind of deprecation, and load_start is still referenced in documentation (link?).

**Comment by Sparticuz** [comment]
It will happen on 0.9.5 whenever it comes out. I'm running a copy built from source. https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9




—

**Comment by thebigmunch** [comment]
Change the name to represent what actually needs to happen. I obviously can't just change them to the new ones, because it would break for anyone with rTorrent < 0.9.5.

 Also, I won't really be looking into this until 0.9.5 actually gets released; autodl-irssi does not support development versions of its dependencies (which is how it should be). If anyone else wants to have a patch/Pull Request ready for when it happens, feel free.

**Comment by thebigmunch** [comment]
FYI, looks like load got changed to load.normal, so you'd have to change load to that in the same line as load_start in MatchedRelease.pm.

**Comment by Sparticuz** [comment]
Ok, is that the only pm file that needs changing or are there other files that have deprecated commands, I can go ahead and make a pull for eventual merging.



—

**Comment by thebigmunch** [comment]
@Sparticuz et al: Give [this](https://dl.dropbox.com/u/20787713/autodl-rt.zip) a try and let me know if everything works okay on the dev version of rTorrent.

**Comment by Sparticuz** [comment]
Sorry, I went back to stable. Turns out my instability with rtorrent was because of Ubuntu, switched distros and now rtorrent works fine. I think that commit looks good though.
