### ISSUE TITLE
{Show} should match the Filter name, not the matched name

### ISSUE THREAD

**Issue by KyleSanderson** [autodl-community/autodl-irssi#75]
There's mixed case matches going on with {Show} from the matched name, I'd much prefer to have them fall underneath the same name.

**Comment by thebigmunch** [comment]
I have no idea what you're talking about. {Show} isn't a thing, and, if you're talking about the $(Show) macro, why would that ever match anything but the captured show name. If you wanted to request a $(FilterName) macro, that would make some sense.

**Comment by KyleSanderson** [comment]
$(FilterName) already exists, and unfortunately is the name of the filter.

I have a Generic Filter with a list of shows
[filter thebigmunch]
shows = CBC Marketplace, Republic of Doyle
upload-type = rtorrent
rt-dir = /Television/$(Show)/$(Resolution)

The problem comes from mixed case matches. If there's a match for CBC MarketPlace, suddenly I have two directories, which isn't desirable by anyone. I'm basically requesting that $(Show) be hooked up to the shows match, if available.

**Comment by thebigmunch** [comment]
$(Show) IS the show match. You're going to have to be more specific. What two directories are you getting?

**Comment by KyleSanderson** [comment]
/Television/CBC Marketplace/720p
/Television/CBC MarketPlace/720p

**Comment by thebigmunch** [comment]
So, the problem here is that the releases are named differently, one with a lowercase `p` and another with an uppercase 'P'. Linux is a case-sensitive OS, so those are two different things to it. autodl-irssi can't really do anything about this; making everything one case would not be a desirable action.

**Comment by KyleSanderson** [comment]
@thebigmunch If autodl-irssi takes the match name for the Show, that would completely fix the issue and improve the UX for everyone using the product.

**Comment by thebigmunch** [comment]
You don't seem to be getting it, so I'll explain it once more before locking this issue. It's matching the name of the show captured from the release name.  You've done a spectacularly terrible job at explaining what you want. Despite that, I think I finally figured out that you want the $(Name) macro to use what you put in the shows filter option (was that so hard?). That's not going to happen for many reasons. Besides just not making sense, the shows filter option can use wildcard characters, and I don't think people would never want those in their directory structure.

The issue lies with the release naming, not in autodl-irssi's behavior.
