### ISSUE TITLE
 Improve Duplicate Release Name Check..

### ISSUE THREAD

**Issue by ne0ark** [autodl-community/autodl-irssi#76]
Similar announce types:

1) this.test.release-test
2) this test release - test
3) this test release test

Is it possible to remove . , (space) and - when checking for dupes. As it is right now all these are not considered dupes.

Thanks

**Comment by thebigmunch** [comment]
I'm pretty sure this has only started happening since the latest release, right? I changed the canonicalization of release names to only include some punctuation where it previously included all of them. This was to make easier the matching of titles with said punctuation in them. I don't know if I'd want to change them back; this seems more of an issue of people changing the release names when they shouldn't be.

PS: 1 and 2 in your examples should still be considered dupes, it's number 3 that wouldn't be.

**Comment by thebigmunch** [comment]
Now that I've had a bit of time to get the blood flowing this morning, this might also affect the auto extraction of the last segment of the release name before the release group when separated by a hyphen. I'll have to check that out and confirm later. If that's the case, then the decision will be made for me.

**Comment by ne0ark** [comment]
Yes it's the number 3. RTT uses number 3 format Announce.

**Comment by ne0ark** [comment]
To find the release group named it should be after - or space before last word. I will check if it's doable with a regex.

**Comment by thebigmunch** [comment]
@ne0ark: Give [this](https://dl.dropbox.com/u/20787713/TextUtils.pm) a try to see if it behaves as expected for you.

**Comment by ne0ark** [comment]
Yep it works. Thanks
