### ISSUE TITLE
Update autodl-irssi to v1.60 or greater by October 31, 2015!!!

### ISSUE THREAD

**Issue by thebigmunch** [autodl-community/autodl-irssi#92]
With autodl-irssi's updater code being updated to use GitHub's Releases API [#89], a standalone update server is no longer necessary. Versions and update files are obtained directly from GitHub as of v1.60. Running an update through the /autodl commands or through the ruTorrent plugin now will prevent you from having to manually update autodl-irssi or the tracker files after the update server is shut down.

**Comment by Hotcooler** [comment]
![clipboard02](https://cloud.githubusercontent.com/assets/4125481/10434732/02bdd3b8-7124-11e5-9ca0-934947b6fee2.png)

Is that a normal response for update/what's new after 1.60 update? Since due to this I had to manually update the tracker files, and well.. if it's normal - it would be rather nice to clean that error message up so it says something that makes sense.

Also I would try to rephrase the 
>Running an update through the /autodl commands or through the ruTorrent plugin now will prevent >you from having to manually update autodl-irssi or the tracker files after the update server is shut >down.

To something like "Running the update now, will save you from manually updating it later." Since for non native English speaker "prevent you from having to manually update" sounds a bit like if you update now, you cant manually update. All in all I just don't like the phrasing.

**Comment by thebigmunch** [comment]
> To something like "Running the update now, will save you from manually updating it later." Since for non native English speaker "prevent you from having to manually update" sounds a bit like if you update now, you cant manually update.

So, the only difference is you added a comma (which is incorrectly used) and removing the word 'having' which is crucial to the meaning of the statement I was making. Not gonna happen.

Regarding the update checking issue: A few others have reported (3, to be exact) have reported such an occurance in the IRC channel. Just like the previous issue which was a result of outdated Perl libs and/or OpenSSL, I don't provide support for local server issues. If someone can show that it's something in autodl-irssi, then I'll fix it. But there have been over 8000 successful trackers downloads from GitHub Releases so far, so it's probably not something in autodl-irssi.

**Comment by Hotcooler** [comment]
Emphasis was on changing "prevent", to some other word and slightly rephrasing resulting message. Though it might just be me.

As for update issue, I'm sure it's not autoDL's fault, though it'd be nice to have the error message say something other than "Update autodl check cancelled!" or at least pass along some useful info, since timeout happens only 5 minutes later and I easily could've missed it.

**Comment by thebigmunch** [comment]
Prevent, like pretty much every other word, is neutral. Any positivity or negativity is from the context in which it is used. In this case, you'd be preventing yourself from needing to do extra work to update than necessary. That sounds like a positive thing to me.

**Comment by TuvixHosting** [comment]
we have the latest 1.60 but we are getting errors
 ERROR:  Could not check for autodl updates: Update autodl check cancelled!
 ERROR:  Could not check for trackers updates: Update trackers check cancelled!

this happens on several servers in different datacenters
but other servers with exact same setup dont have this issue.

any help appreciated as our clients are in need

**Comment by thebigmunch** [comment]
When that error is reached on a server, try the following command on that server: ``curl -s https://api.github.com/rate_limit``. This will show whether that server is hitting the unauthenticated rate limit for the GitHub API. Under most circumstances, this shouldn't happen.

If it's not an issue with the rate limit, then there's nothing that leads me to believe there's an issue within autodl-irssi itself. If someone finds that to be incorrect, please let me know.

**Comment by TuvixHosting** [comment]
this is the output

" 
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 56,
      "reset": 1445378520
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1445375043
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 56,
    "reset": 1445378520
  }
}
" 


But so you know, almost all our servers in different datacenters but also from other providers, with version 1.60 show this issue.
so it is not just us on 1 server.

We spoke to 8 other providers that all have this issue.

**Comment by TuvixHosting** [comment]
update!!! For anyone having this issue, login as root into ssh and cpan
if not installed it will install, just confirm with pressing Enter
once installed type cpan again and then upgrade

this takes a long time, about half an hour, maybe more
but it does solve the issue.

ofcourse reboot after cpan is done

**Comment by Froggaard** [comment]
Nice TuvixHosting!
This worked for me =]
